### ISSUE TITLE
Use touchscreen to control phone?

### ISSUE THREAD

**Issue by Krakuanen** [BimmerGestalt/IDriveConnectAddons#11]
I find the screen mirroring very useful, especially for car navigation with Google maps or Waze. If the touchscreen on the car could be used to control the phone it would be even better. Then there would be no need for developing Mapbox. Would that be possible?

**Comment by hufman** [comment]
As far as I know, there is no way to receive touchscreen coordinates over this app protocol. The car translates any touches into a high-level button press.

**Comment by Vasmares** [comment]
@hufman were you able to look into this again ?

Also: Is this possible?
Would be the ultimate solution :D

https://github.com/BimmerGestalt/IDriveConnectAddons/issues/14

**Comment by hufman** [comment]
As far as I know, there is no way for the car to send touchscreen touches to the app.

**Comment by Vasmares** [comment]
ok. Would have been nice :D
