### ISSUE TITLE
Podcast addict won't allow any interactions

### ISSUE THREAD

**Issue by idesignstuff** [BimmerGestalt/IDriveConnectAddons#13]
It only plays a podcast. It won't allow FF or rewind, either with left/right store buttons under center display or by steering wheel up/down media buttons. When it's interrupted by any other message, it stops and won't start again, even with the media power button cycling.

**Comment by hufman** [comment]
Which Addon are you using? Screen Mirroring doesn't provide any input capabilities.

**Comment by idesignstuff** [comment]
I'm sorry I filed this in addons, when it is the built-in functionality that I was describing.

**Comment by idesignstuff** [comment]
Closing here to open elsewhere
