### ISSUE TITLE
There is no audio in the applications

### ISSUE THREAD

**Issue by Vinsvens** [BimmerGestalt/IDriveConnectAddons#15]
hello, first of all thank you for this great application. I just installed it in an F21 with NBT professional navigation, I can connect and get the Spotify applications through USB, but I don't have audio in the car, nor can I modify the volume with the radio. What could it be? 
Thank you very much

**Comment by hufman** [comment]
Thank you for reaching out!
Audio over the USB Apps connection is not supported except for very old phones running Android Nougat. AAIdrive should show a message saying that Audio Context is not supported. You should tell your car to play Bluetooth Music from your phone, and use AAIdrive for an enhanced control interface.

**Comment by Vinsvens** [comment]
Thank you very much, it worked for me. Very good app
