### ISSUE TITLE
Connection problem after upgtate

### ISSUE THREAD

**Issue by Simonecoach** [BimmerGestalt/IDriveConnectAddons#16]
After upgrade version aaldrive 1.4.1 and mini connect 2.12.3 it's impossible create app connection.
Bluetooth working weel for call but no data transfer.
Please help

**Comment by hufman** [comment]
There haven't been any changes to the connection logic in AAIdrive, but MyBMW/Mini seems to have troubles connecting over Bluetooth after version 2.10: https://github.com/BimmerGestalt/AAIdrive/issues/638
Please complain to BMW and downgrade to Mini 2.9.
