### ISSUE TITLE
Is there a way to disable approval screen mirror popup?

### ISSUE THREAD

**Issue by DrTermi** [BimmerGestalt/IDriveConnectAddons#17]
Hey, 

I was looking in the code but i cant figured out if there is a way to approve automatically the screen recording(mirror) popup just by clicking in the idrive icon app and not having to each time pick up the phone and approve?

Thanks in advance.

**Comment by hufman** [comment]
Besides the permission prompt, the app could theoretically gain the CAPTURE_VIDEO_OUTPUT permission and avoid the permission prompt, but that requires root access on the phone to [install the APK into /system/app](https://stackoverflow.com/a/9645224/169035). Except, they removed that option in Android 10. I don't know of any other way to skip the permission prompt.
