### ISSUE TITLE
How to set up AndrOBD?

### ISSUE THREAD

**Issue by butterflywaltz** [BimmerGestalt/IDriveConnectAddons#19]
Maybe some more detailed instructions please? Have installed the plugin and AndrOBD, how to connect the two?

**Comment by hufman** [comment]
This experiment didn't work out super well, AndrOBD really wants there to be an OBD connection to the car, and so the Addon can't easily add datapoints by itself.
I'm planning to abandon it and just write a standalone CSV logger, or someone can take the logic and make a dedicated visualizer from it.
