### ISSUE TITLE
How to enable screen mirroring?

### ISSUE THREAD

**Issue by blaise365** [BimmerGestalt/IDriveConnectAddons#2]
I've downloaded the apk and nothing happens...it is also not an app that can be launched on my phone. I have a Mini that doesn't have any network connections. Is it that it only works if you have wifi in the vehicle to connect the mirroring connection?

**Comment by hufman** [comment]
Good news! The Screen Mirroring Addon does not use the car's wifi connection.
However, it does require the AAIdrive Addon functionality, which is currently only in the nightly builds. I'm guessing you are running the 1.3 release. Just install the nightly build and a new Addons tab should show up in AAIdrive, showing any installed Addons you have.

**Comment by blaise365** [comment]
Yes I am running 1.3. I guess I never installed the sentry version. I'll give it a go, thank you so much!

Edit: I might be looking in the wrong section, I can't find the nightly builds!

**Comment by hufman** [comment]
If you search in the Readme for "nightly" you should find the link, for the future.
Alternatively, version 1.3.1 was just released yesterday, which includes this feature.
