### ISSUE TITLE
Screen Mirroring - Could not locate Smartthings Classic APK in external directory

### ISSUE THREAD

**Issue by Sleachga** [BimmerGestalt/IDriveConnectAddons#23]
I'm getting the following on my Samsung S22 Ultra:

```
Execution failed for task ':screen_mirror:confirmRHMIResources'.
> Could not locate Smartthings Classic APK in external directory
```

Is there a specific APK I need to download to my phone to get this app to work?  Looked into installing https://www.apkmirror.com/apk/smartthings/smartthings-smartthings/smartthings-smartthings-2-20-1-release/#downloads but this still seems to be broken

**Comment by hufman** [comment]
If you want to build this app yourself, you need to add Smartthings 2.3.1 to the /externals directory of the project:
https://github.com/BimmerGestalt/IDriveConnectAddons/blob/main/external/README.md
