### ISSUE TITLE
Cds gauges

### ISSUE THREAD

**Issue by Leek78** [BimmerGestalt/IDriveConnectAddons#24]
Cds gauges apk not working
![Screenshot_20240220_152828_Package installer](https://github.com/BimmerGestalt/IDriveConnectAddons/assets/160627547/811e7464-5e87-441b-a7a6-ed2ccb66b634)

**Comment by hufman** [comment]
Good catch! I focused on screen_mirror in adding the release keys, and missed the others.

**Comment by Leek78** [comment]
Just tried again, and still not working.

**Comment by hufman** [comment]
My first attempt failed and still produced unsigned APKs, the second attempt worked.
