### ISSUE TITLE
Screen Mirror - Full screen

### ISSUE THREAD

**Issue by ccotyc** [BimmerGestalt/IDriveConnectAddons#3]
Hello,
Is there a way to enable screen mirror to display full screen navigation? Now it runs in a window, about 66% of the navigation screen .
Regards,

**Comment by hufman** [comment]
Full screen mirroring display is not currently implemented. It would be possible to apply some negative padding, similar to how the AAIdrive's [custom map module](https://github.com/BimmerGestalt/AAIdrive/blob/8aab115a54ec96f69e6ac14ba1cd35bd3125dc5d/app/src/main/java/me/hufman/androidautoidrive/carapp/FullImageView.kt#L114-L118) does it, except the car will continue drawing some UI elements on top which I felt would interfere with mirroring, and so I opted to not include support at this time.

**Comment by ccotyc** [comment]
It's true that the car draws in the top, only in the upper right corner - the phone signal, the music source and the time. They are small anyway, and would not interfere too much with the image of the phone compared to having a full screen image. Also, the car draw the red arrow on the left from the back menu.
It's a very useful application, with its addons, the way it works impressed me!
Great job done!

**Comment by dancadar** [comment]
Isn't it a way to trigger a true full screen, like when it's playing a video?

**Comment by hufman** [comment]
The screen mirroring support reuses an existing app structure and its image widget, so it is not able to trigger IDrive's video playback mode.

**Comment by bogdan-calapod** [comment]
I think this can be closed, as the latest screen mirroring addon has a large display by default ?

**Comment by hufman** [comment]
I suppose that's true! f4347f2 implemented this, as much as is possible.
