### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by pedrot84** [BimmerGestalt/IDriveConnectAddons#6]
Hello

how can I install the addons?

thank you

**Comment by hufman** [comment]
You would download the APK for the addon from [the Releases page](https://github.com/BimmerGestalt/IDriveConnectAddons/releases/tag/latest_build) and install it on your phone, and it should then show up in the AAIdrive phone interface.

**Comment by pedrot84** [comment]
Ohhh

Didn't realise there are apk to install, will try tomorrow 

Sorry!

**Comment by Nipaz24** [comment]
Hi,

Which of APK-files should I choose for Android 13 phone?
I have not succeeded to install the add-on APK-file. It says the file is not valid.
Thank you for your help?

**Comment by hufman** [comment]
Hmmm some phones might not like the debug cert used by those files, I'll see about enabling release builds for them.

**Comment by CatCookie** [comment]
So i had the same issue with a OnePlus 8 Pro with Android 13.

I could easily install them via `adb install` and USB Debugging

**Comment by Nipaz24** [comment]
Please send a note once available.

**Comment by hufman** [comment]
The addons are now built with Release keys and should no longer cause you any problems.
